Major network rework 3
SKN-Telephoners/AGH-IX pull request #53
Opened 2022-08-10 18:47 UTC by ddominet

Preparation for vxlan, zerotier, gre-tap common network fabric,
Major Fixes related zerotier.py module,
docker-compose modified,
introducing separated network infra for services

2022-08-10 18:55 UTC, PiotrWodecki requested changes
Please don't commit the .idea folder

2022-08-10 19:34 UTC, ddominet reviewed
Done

2022-08-10 20:19 UTC, PiotrWodecki requested changes

2022-08-10 20:19 UTC, PiotrWodecki commented on core/zerotier.py
> +        if data == None:
use `is` when comparing to `None`

2022-08-10 20:19 UTC, PiotrWodecki commented on requirements.txt
> +docker
Please specify the newest version so dependabot can help us keep the image up-to-date

2022-08-10 20:19 UTC, PiotrWodecki commented on docker-compose.yml
> +      - /var/run/docker.sock:/var/run/docker.sock
This is incredibly dangerous as it gives **root access on the host machine** to anyone that can access this socket inside the container. This cannot go through and we need to find a workaround. More reading material on this topic https://integratedcode.us/2016/04/08/user-namespaces-sharing-the-docker-unix-socket/

2022-08-11 23:19 UTC, ddominet commented
Branch Discontinued,
Fixes introduced in API branch

2022-08-11 23:19 UTC, closed without merging