Major network rework api version
SKN-Telephoners/AGH-IX pull request #55
Opened 2022-08-11 23:34 UTC by ddominet

-introducing Network separation
- creating Flask API with basic Auth to handle requests from code and execute commands on the container
- creating handlers for this API, and integrating it into code

2022-08-13 12:56 UTC, PiotrWodecki requested changes

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +    "aghix": generate_password_hash("JacekRzasa"),
Create this hash from a shared secret

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +        if not user == "aghix":
should be something like `not in users`

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +def login_required(f):
We should only allow login with the source ip of the django container

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +shell2http.register_command(
Remove if not used

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/docker-compose.yml
> +    container_name: test-app
rename container and image to something descriptive

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/docker-compose.yml
> +    ports:
I think there's no need for exporting ports to the host machine, `expose` probably is enough

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/Dockerfile
>  RUN echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf
This should be a file that will be copied instead of `echo >`

2022-08-13 12:56 UTC, PiotrWodecki commented on core/zerotier.py
> +import docker
Import is not used

2022-08-13 12:56 UTC, PiotrWodecki commented on requirements.txt
> +docker==5.0.3
`docker` isn't required anymore

2022-08-13 12:56 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +shell2http.register_command(
This isn't used - remove if not required

2022-08-13 13:00 UTC, ddominet commented on core/zerotier.py
> +import docker
Sure

2022-08-13 13:00 UTC, ddominet commented on requirements.txt
> +docker==5.0.3
Sure

2022-08-13 13:02 UTC, ddominet commented on docker/zerotier/docker-compose.yml
> +    container_name: test-app
This docker compose is there for testing purposes, not required for the solution to work

2022-08-13 13:03 UTC, ddominet commented on docker/zerotier/Dockerfile
>  RUN echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf
I don't think thats necessary

2022-08-13 13:05 UTC, ddominet commented on docker/zerotier/app.py
> +shell2http.register_command(
This is used

2022-08-13 13:06 UTC, ddominet commented on docker/zerotier/app.py
> +shell2http.register_command(
This was included for testing purposes, I would still include it in this release, but remove it later

2022-08-13 13:07 UTC, ddominet commented on docker/zerotier/app.py
> +shell2http.register_command(
It's very important, it makes server join zerotier network

2022-08-13 13:08 UTC, ddominet commented on docker/zerotier/app.py
> +    "aghix": generate_password_hash("JacekRzasa"),
What do you mean? Could you please elaborate?

2022-08-13 14:21 UTC, ddominet reviewed
Check it out now

2022-08-13 14:21 UTC, ddominet commented on docker/zerotier/app.py
> +def login_required(f):
I've tried it, but it's very problematic to do, you can't use DNS names because zerotier-controller can't resolve it because it uses host networking. You can't just write down the first IP that tries to connect because code restarts during migration and IP is different

2022-08-13 14:21 UTC, ddominet commented on docker/zerotier/app.py
> +shell2http.register_command(
Removed

2022-08-13 14:21 UTC, ddominet commented on docker/zerotier/docker-compose.yml
> +    ports:
It's a docker-compose to start this container independently without code, purely for testing purposes

2022-08-13 14:21 UTC, ddominet commented on requirements.txt
> +docker==5.0.3
Done

2022-08-13 14:22 UTC, ddominet commented on docker/zerotier/app.py
> +        if not user == "aghix":
Done

2022-08-13 14:22 UTC, ddominet commented on docker/zerotier/app.py
> +    "aghix": generate_password_hash("JacekRzasa"),
This is a shared secret

2022-08-13 20:02 UTC, PiotrWodecki requested changes

2022-08-13 20:02 UTC, PiotrWodecki commented on docker/zerotier/app.py
> +    "aghix": generate_password_hash("JacekRzasa"),
@ddominet It's not a "secret" because it's in plaintext. It should be impossible to accidentally deploy agh-ix with a key that's open-source in this repository. 

Additionally, to even change this hash, you need to perform a lot of changes in the source code: https://github.com/SKN-Telephoners/AGH-IX/blob/00f0e99a4efc1cc95d566b84b48e00412ef1635b/core/zerotier.py#L12
https://github.com/SKN-Telephoners/AGH-IX/blob/00f0e99a4efc1cc95d566b84b48e00412ef1635b/core/zerotier.py#L166
https://github.com/SKN-Telephoners/AGH-IX/blob/00f0e99a4efc1cc95d566b84b48e00412ef1635b/core/zerotier.py#L178
etc.

I would personally try to read a string from a file that is loaded into both containers using docker secrets. If it is set to something invalid, it would force the user to initialize it before deployment or development. Also, it would be the single source of truth and wouldn't require many code changes. 
Of course other ideas are also welcome

2022-08-13 20:02 UTC, PiotrWodecki commented on docker/zerotier/Dockerfile
>  RUN echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf
Sure

2022-08-15 21:02 UTC, PiotrWodecki approved these changes
We need a different approach to waiting for ZT service to start. It would prevent 500 errors on startup, but I think it's better we do it under another task.

Please merge if you agree with my changes.

2022-08-16 08:16 UTC, merged